// <auto-generated />
using System;
using FormulaABD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaABD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240923115804_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormulaABD.Models.Pilota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Piloti");
                });

            modelBuilder.Entity("FormulaABD.Models.Risultato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PilotaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Posizione")
                        .HasColumnType("int");

                    b.Property<int>("PunteggioDistacco")
                        .HasColumnType("int");

                    b.Property<int>("PunteggioPosizione")
                        .HasColumnType("int");

                    b.Property<string>("TempoGiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalePunteggioGara")
                        .HasColumnType("int");

                    b.Property<Guid>("TracciatoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PilotaId");

                    b.ToTable("Risultati");
                });

            modelBuilder.Entity("FormulaABD.Models.Tracciato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tracciati");
                });

            modelBuilder.Entity("FormulaABD.Models.Risultato", b =>
                {
                    b.HasOne("FormulaABD.Models.Pilota", "Pilota")
                        .WithMany()
                        .HasForeignKey("PilotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pilota");
                });
#pragma warning restore 612, 618
        }
    }
}
